### ISSUE TITLE
UI improvements to WebTSA

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2DataSharingPortal#236]
People over at Stroud *really* don't like the some of the features "missing" from WebTSA:

- [x] no ability to "trace" a line and see individual point values (https://github.com/UCHIC/WEBTSA/issues/120)
- [x] upper visualization pane can't be used to control pan/zoom, only lower pane (https://github.com/UCHIC/WEBTSA/issues/121)
- [x] lack of any vertical zoom (https://github.com/UCHIC/WEBTSA/issues/122)

**Comment by horsburgh** [comment]
After discussing this on the phone last week, @Maurier suggested adding zoom capabilities to the upper plot using the mouse scroll wheel. Panning through time would still be done on the lower pane as it is now.

The ability to trace the line and see individual points may be more difficult to implement because the code actually "thins" the data to make it plot faster (e.g., when you show a very long time series and you are zoomed out, TSA does not plot every point because you could not visually perceive every point and it would take unnecessarily long time to draw). 

@Maurier - is it still implemented this way? Is there a point at which you've zoomed in far enough that all of the points are plotted and you could trace the data? The implication is that when hovering you would only see the points that get plotted and not all of the points and so it might be misleading for users.

**Comment by horsburgh** [comment]
These look really awesome. We had demos from @Maurier yesterday, and I just tested on the sandbox today. The following have been added:

* Vertical zooming/scaling by hovering mouse over a y-axis and using the mouse scroll wheel or track pad to zoom in or out.
* Vertical dragging by clicking on the values of a y-axis and dragging up or down
* Horizonal zooming/scaling by hovering over the plot area and using the mouse scroll wheel or track pad to zoom in or out
* Horizontal scrolling continues to be controlled via the thumbnail plot at the bottom of the screen.
* Individual data values are shown for all plotted time series by hovering over the plot area and dragging mouse left or right

Adding the "tested" label.

**Comment by aufdenkampe** [comment]
These do look awesome.

There is one additional set of tweaks to the X-Axis (time), however, which I think is quite important.

The X-Axis labels make it really hard to see the time frame that you are looking at, especially the Year, which is not shown anywhere. 

I recommend these changes to the X-Axis labels:
* Add a global X-Axis label that includes Time Zone information, such as "DateTime in UTC" or preferably "DateTime in UTC-6 (Central Daylight Time)". 
  * Presently timezone is not listed anywhere, and it seems that it is all in UTC. At a minimum, this needs to be listed somewhere. Optimally, we would display in local time or allow a user to set the time zone, but I understand that we might not be able to implement that now under current constraints.
* Always show Year, but preferably not for every Tick mark. Can it be shown for just the first and last tick mark?
* Remove days of the week from the Tick Labels. Not only are they not really necessary, but they make it much harder to see the Month labels, especially when zoomed in. Replace with Month.
* Remove the hour Tick Labels entirely and just show the tick marks for hours. These labels are not really necessary given that the wonderful feature when hovering a mouse over the plot that shows all the values and the full timestamp for a given X value.

@Maurier, Let me know what you think, and if any of these changes can be easily made.

**Comment by horsburgh** [comment]
@aufdenkampe - these are good ideas, but I'm going to ask @Maurier to hold off on any new development on TSA until we at USU decide what we can and can't do with other funding. I suggest moving this to a new issue as this one will get closed as soon as we've verified that the fix for the original issue as reported is deployed on production (which it should be now).

**Comment by horsburgh** [comment]
Improvements to the TSA UI that meet the original issue are live on production. Closing.
