### ISSUE TITLE
Checklist: Test staging web + production database

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#419]
### **Pre-Production** = staging web server + production database server 

Just prior to release, we will point the staging web server to the production database server.

AFTER we do this, we will do a 2nd round of testing, which will include a general set of tests and release-specific tests.

**General Tests**, confirming the the following work:
- [x] Data values up to date?
  - Compare "Last Measurement" times between https://staging.monitormywatershed.org/sites/ and https://monitormywatershed.org/sites/
- [x] Sparkline plots?
  - Pick a recently updated site, such as https://staging.monitormywatershed.org/sites/MeteoTsu-1/, and confirm that the 72-h plots are up to date.
- [x] TSA connecting, plotting, downloading?
  - such as http://staging.monitormywatershed.org/tsa/?sitecode=MeteoTsu-1&view=datasets&plot=false
- [x] Edit station, add sensor?
- [x] Check for newly added sensors and output variables (in main UI and also Admin Panel)

**Release-Specific Tests**
- [x] Scan through & test issues in Milestone for the release
  - https://github.com/ODM2/ODM2DataSharingPortal/milestone/13?closed=1
- [x] Color of map symbols does not correctly align with real data updated time #383

**Comment by aufdenkampe** [comment]
@tslawecki, this looks good to me. Let's push the release!
