### ISSUE TITLE
Checklist: Final test of new Release on Production

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#420]
AFTER we:
- Test staging web + production database (#419), and
- Switch IP addresses to promote the staging server to production.

**General Tests**, confirming that the following work:
- [x] Data values up to date?
- [x] Sparkline plots?
- [x] TSA connecting, plotting, downloading?
- [x] Edit station, add sensor?

**Release-Specific Tests**
- [x] Scan through & test issues in Milestone for the release
  - https://github.com/ODM2/ODM2DataSharingPortal/milestone/13?closed=1
