### ISSUE TITLE
Pre-Release 0.11 Pre-Production test checklist

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#454]
### **Pre-Production** = staging web server + production database server 

Just prior to release, we will point the staging web server to the production database server.

AFTER we do this, we will do a 2nd round of testing, which will include a general set of tests and release-specific tests.

**General Tests**, confirming the the following work:
- [x] Data values up to date?
  - Compare "Last Measurement" times between https://staging.monitormywatershed.org/sites/ and https://monitormywatershed.org/sites/
- [x] Sparkline plots?
  - Pick a recently updated site, such as https://staging.monitormywatershed.org/sites/CWS-ThomasDairy1/, and confirm that the 72-h plots are up to date.
- [x] TSA connecting, plotting, downloading?
  - such as http://staging.monitormywatershed.org/tsa/?sitecode=CWS-ThomasDairy1&view=datasets&plot=false
- [x] Edit station, add sensor?
- [x] Check for newly added sensors and output variables (in main UI and also Admin Panel)
- [x] WOFpy web services?
  - https://staging.monitormywatershed.org/wofpy

**Release-Specific Tests**
- [x] Scan through & test issues in Milestone for the release
  - https://github.com/ODM2/ODM2DataSharingPortal/milestone/14?closed=1

Checklist copied from #419

**Comment by HeatherBrooks** [comment]
@aufdenkampe Not in your checklist above, but I registered a new site and created a leaf pack experiment. Things look good except the title and legend are missing from the second chart. Also, when I tried to download a CSV of the data I got "Server Error (500)", not sure if that's expected at this stage?

[https://staging.monitormywatershed.org/sites/WCC_US1/leafpack/27/](https://staging.monitormywatershed.org/sites/WCC_US1/leafpack/27/)

**Comment by aufdenkampe** [comment]
@HeatherBrooks, thanks for doing a release-specific test. I don't think either error should occur.

@htaolimno, can you look into these two issues, which I don't think should be occurring:
- [ ]  Missing title and legend for second chart of a new Leaf Pack experiment
- [ ] Get a "Server Error (500)" when downloading a CSV

**Comment by htaolimno** [comment]
@HeatherBrooks csv download still calls the old Biotic Index calculation and that caused error. I'll fix that. I'll also look into the other issue - have to figure out why occurs on production database.

**Comment by htaolimno** [comment]
@HeatherBrooks fixed broken csv download.

**Comment by HeatherBrooks** [comment]
@htaolimno Thanks for fixing the csv download. 

Just to clarify, in Anthony's checklist above "Missing title and legend for second chart of a new Leaf Pack experiment" you can remove the word "new" as the title and legend don't appear on pre-existing experiments either. See [https://staging.monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/](https://staging.monitormywatershed.org/sites/BogBrook_Rt312/leafpack/4/)

**Comment by htaolimno** [comment]
@HeatherBrooks : seems that an older version of barchart.js file is used and that caused missing title and legend on the chart. Let me check a few things.

**Comment by htaolimno** [comment]
@HeatherBrooks Think I figured it out - I should have run "collectstatic" command to collect static files on the server and that's why the latest version of barchart.js was not picked up.

**Comment by HeatherBrooks** [comment]
@htaolimno Yep, the title and legend are back. Thanks!

**Comment by aufdenkampe** [comment]
@htaolimno, thanks for figuring this out. Please add the "run `collectstatic` command" to our workflow documentation wiki.

All, does everything else check out?

**Comment by dbressler75** [comment]
@aufdenkampe, it looks great!  I tested first three bullets and all worked well.  Also tested various other things, downloading from panels, main download tabs, plotting in tsa.  The tsa x axis zooming and y axis dragging and zooming work much nicer now!  

I apologize for the last minute questions and I'm guessing these are fixes for later but here are a few things: 1) is the size of csv files that can be uploaded going to be increased? (currently it's ~1wk or data)  2) is there a way to show/confirm when files are being downloaded 3) tsa y axis inputting axis range? (i.e., same as that option for x axis).  Thanks Anthony!

**Comment by aufdenkampe** [comment]
@dbressler75, thanks for that testing! I'm glad to hear things are working well for you.

Unfortunately, there were a number of issues in our [Release 0.11 - Leaf Pack update + minor features & fixes](https://github.com/ODM2/ODM2DataSharingPortal/milestone/15) milestone that we needed to postpone to future work, including the CSV-related issues #430, #443, etc.

Fortunately, the ability to modify the TSA x-axis and y-axis ranges has been working for a long time (since Aug. 2018, see #236). Do it by hovering your pointer over the axis and dragging to shift the axis and wheel-scrolling (or two finger trackpad swiping) to resize the axis. For details, read https://github.com/ODM2/ODM2DataSharingPortal/issues/236#issuecomment-408218332.

**Comment by aufdenkampe** [comment]
@tslawecki, we are ready for Release 0.11 to production tomorrow morning!

**Comment by dbressler75** [comment]
Hey Anthony,
Thanks for the feedback.

Re "Fortunately, the ability to modify the TSA x-axis and y-axis ranges has
been working for a long time (since Aug. 2018, see #236
<https://github.com/ODM2/ODM2DataSharingPortal/issues/236>). Do it by
hovering your pointer over the axis and dragging to shift the axis and
wheel-scrolling (or two finger trackpad swiping) to resize the axis. For
details, read #236 (comment)
<https://github.com/ODM2/ODM2DataSharingPortal/issues/236#issuecomment-408218332>."
- yes that is a very nice feature, but for the Y axis I was talking about
incorporating an option to actually enter specific ranges for that axis (as
opposed to dragging/scrolling with mouse or pad) - you can do this on the
x-axis in the upper right calendar selection option and it seems like it
would be useful to be able to do the same for the parameter(s) values
displayed on the y-axis.  Not a huge issue and not nearly as important
seemingly as the csv upload size issue.

David W. Bressler
Citizen Science Project Facilitator
Stroud Water Research Center
410-456-1071 (mobile)
610-268-2153 x312 (office)
dbressler@stroudcenter.org

**Comment by aufdenkampe** [comment]
@dbressler75, thanks for explaining.

Adding an exact Y-axis min/max data entry option isn't a feature that was ever on my/our radar. 

Could you create a new issue describing your request for this feature? Our approach to developing this portal is that we work on things that are described in issues, to avoid missing requests like this one that we hadn't heard.

**Comment by dbressler75** [comment]
Anthony,
Very sorry, I thought I had put this into github at some point but I guess
I didn't.  I just added it
https://github.com/ODM2/ODM2DataSharingPortal/issues/457

Thanks very much for all the great work on this!

-Dave

David W. Bressler
Citizen Science Project Facilitator
Stroud Water Research Center


410-456-1071 (mobile)
610-268-2153 x312 (office)
dbressler@stroudcenter.org

**Comment by aufdenkampe** [comment]
@dbressler75, thanks for creating the new issue!
