### ISSUE TITLE
Post-Release 0.11 Production test checklist

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2DataSharingPortal#455]
AFTER we:
- Test staging web + production database (#454), and
- Switch IP addresses to promote the staging server to production.

**General Tests**, confirming that the following work:
- [x] Website renders for all mirrored domains?
  - https://monitormywatershed.org and https://www.monitormywatershed.org
  - https://data.wikiwatershed.org
  - https://data.envirodiy.org
- [x] Data values up to date?
  - Pick a recently updated site, such as https://monitormywatershed.org/sites/CWS-ThomasDairy1/
- [x] Sparkline plots?
  - Scroll down to plots for a recently updated site, such as https://monitormywatershed.org/sites/CWS-ThomasDairy1/, and confirm that the 72-h plots are up to date.. Those plots should be green and with data. Other variables were turned off and should be red with no recent data.
- [x] Edit station, add sensor?
- [x] TSA connecting, plotting, downloading?
  - Try http://monitormywatershed.org/tsa/?sitecode=CWS-ThomasDairy1&view=datasets&plot=false
- [x] WOFpy web services?
  - https://monitormywatershed.org/wofpy

**Release-Specific Tests**
- [x] Scan through & test issues in Milestone for the release
  - https://github.com/ODM2/ODM2DataSharingPortal/milestone/14?closed=1

Checklist copied from #420

**Comment by HeatherBrooks** [comment]
@aufdenkampe I'm getting "Bad Request (400)" for [https://www.monitormywatershed.org/](https://www.monitormywatershed.org/).

**Comment by aufdenkampe** [comment]
@HeatherBrooks, thanks for noticing that. @tslawecki & @htaolimno, can you look into it?

**Comment by tslawecki** [comment]
This has been fixed manually. The django settings file


  /etc/envirodiyconfig/ODM2DataSharingPortalConfig/django/settings.json


needed to have https://www.monitormywatershed.or<http://www.monitormywatershed.org>g added to the allowed hosts. I have made the change on the production server; this should be updated on the configuration repository at some point.


________________________________

**Comment by aufdenkampe** [comment]
@HeatherBrooks, @SRGDamia1, @htaolimno. Does everything work? Check off items on the list as you confirm.

Thanks

**Comment by HeatherBrooks** [comment]
@aufdenkampe I have checked the leaf pack experiment data entry workflow and all seems to be working well. Other than the nagging sitewide problem of being served http rather than https, that is.

**Comment by aufdenkampe** [comment]
@HeatherBrooks, its good to know that the site is mostly working.

However, please describe what you are noticing regarding "sitewide problem of being served http rather than https". I hadn't noticed that, and it might be an easy fix for us. Please create a new issue on this. We want to direct away from HTTP to HTTPS as much as possible.

**Comment by HeatherBrooks** [comment]
@aufdenkampe Sorry I wasn't clear. I brought this up in an email with you @htaolimno and @tslawecki last weekend. Where should I create the new issue?

**Comment by aufdenkampe** [comment]
@HeatherBrooks, I'm sorry that I missed it in our email exchanges!

You can create the issue in this repo, and tag it with the release 0.11 milestone. Also tag me and @htaolimno.
